### ISSUE TITLE
Ingredients always with preparation

### ISSUE THREAD

**Issue by octoshrimpy** [gmso/recipys#1]
Ingredients list never shows up within Ingredients container.

Also it would be cool to highlight the chosen ingredients: 

> recipys breakfast with bacon onions

in ingredients list, bacon and onions are a different color, to show where search is

**Comment by gmso** [comment]
Hi!
Thanks for your feedback and submitting the issue 😃 
Regarding your two points:

> Ingredients list never shows up within Ingredients container.

This was something annoying me too. Unfortunately many recipes are formatted in a weird way, where the ingredients are written together with the preparation. I had something in mind of how to deal with these cases, so I've gone ahead and implemented the changes. In [version 1.1.0](https://pypi.org/project/recipys/1.1.0/), the ingredients are separated from the preparation, if necessary, and put into their corresponding container. Feel free to try this new version and let me know!

> Also it would be cool to highlight the chosen ingredients:

This is a cool idea, I hadn't thought about that! But I see that it could be useful. I will see if I can come around to making this change too.

**Comment by gmso** [comment]
So I've gone ahead and added the coloring of searched meal and/or ingredients. They should be colorized now when you get your search results. This change is implemented in [version 1.2.0](https://pypi.org/project/recipys/1.2.0/). Feel free to try it out!
Since now both points are done, and if it's OK with you, I'll go ahead and close the issue (unless you still have other points you'd like to address 😃)

**Comment by octoshrimpy** [comment]
looks awesome! I'd say the secondary border around both isn't necessary, and what do you think about highlighting the whole line for the searched ingredients, instead of just the word? `chicken` vs `4 chicken breasts, boneless` ?
